### ISSUE TITLE
"Out-of-Distribution Representation Learning for Time Series Classification" code missed

### ISSUE THREAD

**Issue by Howardhuang98** [microsoft/robustlearn#1]
The code of paper "Out-of-Distribution Representation Learning for Time Series Classification" missed. Can you help upload it, or specify where it is? 

` Qualitative and quantitative results demonstrate that DIVERSIFY significantly outperforms other baselines and effectively characterizes the latent distributions. Code is available at: https://github.com/microsoft/robustlearn.`

**Comment by jindongwang** [comment]
You are so fast! We will upload the code for that paper in March, after the camera-ready deadline of ICLR. Stay tuned!

**Comment by jindongwang** [comment]
@Howardhuang98 The code for that paper is added now: https://github.com/microsoft/robustlearn/tree/main/diversify
