### ISSUE TITLE
DIVERSIFY Processed Dataset Link Broken

### ISSUE THREAD

**Issue by Nyquixt** [microsoft/robustlearn#19]
Hi,

Thank you for the awesome work! I try to reproduce the result of the paper, but it seems to me that the dataset link for DIVERSITY is not accessible. Can you take a look?

-K

**Comment by jindongwang** [comment]
Thank you for your interest in this work. I just fixed the link error. Please refresh the page.

**Comment by Nyquixt** [comment]
Thanks for the quick response. The link is now working!

-K
