### ISSUE TITLE
DIVERSIFY preprocessed data emg_y.npy[:, 2] is all 0

### ISSUE THREAD

**Issue by mhzhang96** [microsoft/robustlearn#20]
Hi,

In your DIVERSIFY code, the 【def loaddata_from_numpy】in /datautil/actdata/util.py defines:

x = np.load('.../emg_x.npy')
ty = np.load('.../emg_y.npy')
cy, py, sy = ty[:, 0], ty[:, 1], ty[:, 2]

I suppose cy is class label, py is subject label, but sy is all 0.
I'm confused what does this 【sy】stands for?

Thank you.

**Comment by lw0517** [comment]
Hi, this label is not designed for EMG. Sy means sensor positions in other datasets, e.g. DSADS. In other tasks, we can utilize sy to split datasets.

**Comment by mhzhang96** [comment]
> Hi, this label is not designed for EMG. Sy means sensor positions in other datasets, e.g. DSADS. In other tasks, we can utilize sy to split datasets.

Thank you for your reply! 

Could you share how did you preprocess the data, i.e. the sliding window technique?

Also, could you share how to add Transformer as backbone as mentioned in your paper?

Thanks.

**Comment by lw0517** [comment]
For preprocessing, try the following codes. Slight adaptations might be required.

![image](https://user-images.githubusercontent.com/31000480/228132934-46b9c09a-42dd-4694-b3b0-1be1a464fa99.png)

For other backbones, e.g. Transformer, please replace ActNetwork with your backbones. And make sure that your backbones can return extracted features.

**Comment by mhzhang96** [comment]
> For preprocessing, try the following codes. Slight adaptations might be required.
> 
> ![image](https://user-images.githubusercontent.com/31000480/228132934-46b9c09a-42dd-4694-b3b0-1be1a464fa99.png)
> 
> For other backbones, e.g. Transformer, please replace ActNetwork with your backbones. And make sure that your backbones can return extracted features.

Thank you for your reply, that's very helpful!
