### ISSUE TITLE
The result is different with the readme.md in this repo.

### ISSUE THREAD

**Issue by 17679393389** [microsoft/robustlearn#22]
Hi,Doc Wang.I'm just download the code of Diversify and the dataset,and ran it use your second command that gave in the readme.md file.But my best result is 83.9% which your offer are 88%.I'm just want to know what is the reason? Thank you ,looking forward to your reply.

**Comment by jindongwang** [comment]
Which pytorch version do you use? Did you use the same environment as said in the readme file?

**Comment by jindongwang** [comment]
Please wait for a few days. We are rerunning the program using latest Pytorch version. I know that you may not get the best results as readme using newer version of Pytorch. We have the training logs available online at: https://wandb.ai/luw12thu/diversify.

**Comment by jindongwang** [comment]
Hi @17679393389 I have updated the results and hyperparameters to reproduce the results. Please refresh the code repo and see README file.
