### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'emg/emg_x.npy'

### ISSUE THREAD

**Issue by 943fansi** [microsoft/robustlearn#23]
FileNotFoundError: [Errno 2] No such file or directory: 'emg/emg_x.npy'

**Comment by jindongwang** [comment]
This is a simple error. You need to check your file path.
________________________________
发件人: 943fansi ***@***.***>
发送时间: Saturday, April 22, 2023 9:49:57 PM
收件人: microsoft/robustlearn ***@***.***>
抄送: Subscribed ***@***.***>
主题: [microsoft/robustlearn] FileNotFoundError: [Errno 2] No such file or directory: 'emg/emg_x.npy' (Issue #23)


FileNotFoundError: [Errno 2] No such file or directory: 'emg/emg_x.npy'

―

**Comment by 943fansi** [comment]
Are you sure that you have provided .npy files for emg dataset? The files I download is .txt files.By the way, the default dataset is dsads. What is the ralationship between emg and dsads.Additionaly, there is no traintest.py in the diversity project.It can be frustrating to have a lot of extra operations to get the results.

**Comment by jindongwang** [comment]
We provided the complete code toand data to run the experiments. Please update to the latest code version. This code has been used by many others amd I'm sure there is no problem running them.
________________________________
发件人: 943fansi ***@***.***>
发送时间: Saturday, April 22, 2023 11:25:06 PM
收件人: microsoft/robustlearn ***@***.***>
抄送: Jindong Wang ***@***.***>; Comment ***@***.***>
主题: Re: [microsoft/robustlearn] FileNotFoundError: [Errno 2] No such file or directory: 'emg/emg_x.npy' (Issue #23)


Are you sure that you have provided .npy files for emg dataset? The files I download is .txt files.By the way, the default dataset is dsads. What is the ralationship between emg and dsads.Additionaly, there is no traintest.py in the diversity project.It can be frustrating to have a lot of extra operations to get the results.

―

**Comment by 943fansi** [comment]
Thank you very much for your quick and detailed response. I saw the .npy file and I believe this issue has been resolved. Thank you.
