### ISSUE TITLE
The algorithm setting bug

### ISSUE THREAD

**Issue by WangLabTHU** [microsoft/robustlearn#24]
In the first training example:
python train.py --data_dir ./data/ --task cross_people --test_envs 0 --dataset emg --algorithm Diversify --latent_domain_num 10 --alpha1 1.0 --alpha 1.0 --lam 0.0 --local_epoch 3 --max_epoch 50 --lr 0.01 --output ./data/train_output/act/cross_people-emg-Diversify-0-10-1-1-0-3-50-0.01

--algorithm Diversify
should be:
--algorithm diversify

**Comment by jindongwang** [comment]
Seems you are right. Let me fix this.
