### ISSUE TITLE
Can you upload the other or the whole code for preprocessing the data and codes for different 

### ISSUE THREAD

**Issue by ghost** [microsoft/robustlearn#25]
While going through the paper, I noticed that the provided source code primarily focuses on a small portion of the experiments mentioned. As an aspiring researcher in the field, I would greatly appreciate it if you could kindly provide me with the complete source code, including the data preprocessing and model implementation, for the other experiments. This would enable me to gain a better understanding of your methodology and facilitate my learning of your innovative ideas.
 
I understand that modifying the existing code might be challenging due to its highly integrated nature, which is why I am reaching out to request your assistance. Your support in providing the complete source code would not only enhance my comprehension of your work but also allow me to explore the application of related techniques in my own research.

**Comment by jindongwang** [comment]
@kaying-lai Thanks for asking. Please understand that reorganizing the code and reruning all experiments would take a lot of time. Thus, we currently only support one dataset. I'll ask the first author to release more in the future. But I cannot guarantee that. If your request is urgent, please send another email to me and I can send you the initial code (could be messy).

**Comment by ghost** [comment]
Yeah, actually I have sent the email to request the code. You can check the email, around 2days ago. And I am a hkust student and the email title is "Request for Complete Source Code of OOD Paper"

**Comment by jindongwang** [comment]
@kaying-lai Is your problem solved? Sorry I'm busy these days.

**Comment by Diting-li** [comment]
Dear author, your work is truly amazing, and I have read your paper. I have analyzed your data, and in each person's data, there are multiple samples with the same class label. For example, Person 1 has 12 samples labeled as 0. However, I want to use my own dataset where each person has only one sample and corresponds to a single class, without any duplicates. Can I assume that when restructuring my dataset following your data format, each sample corresponds to a classification category "cy" and a person category "py," and the initial domain category "sy" is 0 for all samples?

**Comment by jindongwang** [comment]
@lw0517

**Comment by lw0517** [comment]
> Reference in new i

Yes, you can follow our data format.
Please note that "sy" is not the initial domain category but the sensor label.
You can generate domain labels according to specific rules, e.g. persons (py).

**Comment by lw0517** [comment]
> Dear author, your work is truly amazing, and I have read your paper. I have analyzed your data, and in each person's data, there are multiple samples with the same class label. For example, Person 1 has 12 samples labeled as 0. However, I want to use my own dataset where each person has only one sample and corresponds to a single class, without any duplicates. Can I assume that when restructuring my dataset following your data format, each sample corresponds to a classification category "cy" and a person category "py," and the initial domain category "sy" is 0 for all samples?

Yes, you can follow our data format.
Please note that "sy" is not the initial domain category but the sensor label.
You can generate domain labels according to specific rules, e.g. persons (py).

**Comment by rcNg0229** [comment]
> Yeah, actually I have sent the email to request the code. You can check the email, around 2days ago. And I am a hkust student and the email title is "Request for Complete Source Code of OOD Paper"

Hi, may I ask if you have got the source code for the paper? Appreciate it if you can share with me and my email is 849672085@qq.com

**Comment by jindongwang** [comment]
@One-one-one-learner The source code is released in this repo. For data processing files, maybe @lw0517 can help?

**Comment by rcNg0229** [comment]
> @One-one-one-learner The source code is released in this repo. For data processing files, maybe @lw0517 can help?

Thanks a lot, it works well now.
