### ISSUE TITLE
Misconfiguration of `stderr` in `diversify.utils.util.py get_args()`

### ISSUE THREAD

**Issue by SagiPolaczek** [microsoft/robustlearn#27]
Hey!
Thanks for open-sourcing you project(s)!

While referencing **chatgpt-robust** for another project, I encountered your usage with `Tee()` in `diversify.utils.util.py`.

Snippets:
```python
class Tee:
    def __init__(self, fname, mode="a"):
        self.stdout = sys.stdout
        self.file = open(fname, mode)

    def write(self, message):
        self.stdout.write(message)
        self.file.write(message)
        self.flush()

    def flush(self):
        self.stdout.flush()
        self.file.flush()
```
```python
    sys.stdout = Tee(os.path.join(args.output, 'out.txt'))
    sys.stderr = Tee(os.path.join(args.output, 'err.txt'))
```

As far as I understand you mix `stderr` with `stdout`. What do you think?
Let me know if you want me to submit a PR and suggest a solution :-)

**Comment by lw0517** [comment]
Thank you for your suggestions. The current code is able to effectively log all the information we need. The 'out.txt' file records all the information, including error messages, while the 'err.txt' file specifically logs Python runtime errors. This meets our current requirements. However, if you have any further suggestions, please feel free to propose them.

**Comment by SagiPolaczek** [comment]
Thanks for the quick and nice comment! will do :)
