### ISSUE TITLE
Request for code from "Generalizable Low-Resource Activity Recognition with Diverse and Discriminative Representation Learning".

### ISSUE THREAD

**Issue by wlesss** [microsoft/robustlearn#47]
I'm recently came across your paper "Generalizable Low-Resource Activity Recognition with Diverse and Discriminative Representation Learning" and found it very interesting. In the paper, you mention that the code can be made publicly available from the link of https://github.com/microsoft/robustlearn, but I couldn't find a specific project from this link. Could you please tell me which project is corresponding to it, or could you please upload the relevant code? I look forward to hearing back from you and thank you for your consideration.

**Comment by jindongwang** [comment]
Thanks for your interest in this work. The code will be released in a week.

**Comment by wlesss** [comment]
Okay, thank you for your timely response and look forward to learning from your work.

**Comment by jindongwang** [comment]
@wlesss Code for the paper is uploaded.
