### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Ma-PC** [microsoft/robustlearn#61]
在跑DDlearn的时候看了一篇您的另一篇文章：
Domain Generalization for Activity Recognition via
Adaptive Feature Fusion
对这篇文章也挺感兴趣的，觉得您这篇文章也很不错。请问这篇文章的代码与设置有吗？希望得到您的回复，谢谢

**Comment by jindongwang** [comment]
这个代码不在我这里，可以给一作发邮件要
